sudo: required

language: python
python:
  - 2.7

services:
  - docker

install:
  - docker build -t mgonzalez/sample-app .

before_script:
  - pip install -r requirements.txt
  - pip install mock
  - pip install requests
  - pip install feedparser

script:
  - docker ps | grep -q blog
  - python tests.py
